/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2018-08-25 07:58:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.menu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme() + "://"+request.getServerName() + ":" + request.getServerPort() + path + "/style/";
System.out.println("basePath:"+basePath);
String basePath2 = request.getScheme() + "://"+request.getServerName() + ":" + request.getServerPort() + path + "/";
System.out.println("basePath2:"+basePath2);

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("   <meta charset=\"utf-8\">\r\n");
      out.write("    <title>test</title>\r\n");
      out.write("\t\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"css/nav.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"font/iconfont.css\">\r\n");
      out.write("\t\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/nav.js\"></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div style=\"height: 60px;background-color: rebeccapurple;text-align: center;font-family: Aharoni;font-weight: bolder;\r\n");
      out.write("  font-size: 40px;line-height: 60px\">\r\n");
      out.write("      test\r\n");
      out.write("  </div>\r\n");
      out.write("    <div  class=\"nav\" align=\"left\" style=\"width: 200px\">\r\n");
      out.write("        <ul>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"javascript:;\"><i class=\"my-icon nav-icon icon_1\"></i><span>j2ee</span><i class=\"my-icon nav-more\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("MainController/springmvcmain.do\" TARGET=\"contentiframe\"><span>springmvc</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("springjdbccontrol/springjdbcmain.do\" TARGET=\"contentiframe\"><span>springjdbc</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("user/index.do\" TARGET=\"contentiframe\"><span>springmvcibatis</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/downfiles.jsp\" TARGET=\"contentiframe\"><span>文件下载</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/servlet.jsp\" TARGET=\"contentiframe\"><span>servlet</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/springwebsocket.jsp\" TARGET=\"contentiframe\"><span>springwebsocket</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/velocity.jsp\" TARGET=\"contentiframe\"><span>velocity</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"javascript:;\"><i class=\"my-icon nav-icon icon_2\"></i><span>技术前沿</span><i class=\"my-icon nav-more\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/redis.jsp\" TARGET=\"contentiframe\"><span>redis</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/websocket.jsp\" TARGET=\"contentiframe\"><span>websocket</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/websocekt_tomcatexample.xhtml\" TARGET=\"contentiframe\"><span>websocekt_tomcatexample</span></a></li>\r\n");
      out.write("                    <li><a href=\"");
      out.print(basePath2);
      out.write("static/jsp/jms.jsp\" TARGET=\"contentiframe\"><span>jms</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"javascript:;\"><i class=\"my-icon nav-icon icon_3\"></i><span>前端</span><i class=\"my-icon nav-more\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>javascript</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>jquery</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>extjs</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>其他</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"javascript:;\"><i class=\"my-icon nav-icon icon_3\"></i><span>关系型数据库</span><i class=\"my-icon nav-more\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>oracle</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>mysql</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>其他</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("                <a href=\"javascript:;\"><i class=\"my-icon nav-icon icon_3\"></i><span>非关系型数据库</span><i class=\"my-icon nav-more\"></i></a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>mongodb</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>redis</span></a></li>\r\n");
      out.write("                    <li><a href=\"javascript:;\"><span>其他</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  <div style=\"text-align:center;background-color: black;height: 60px;font-family: Aharoni;font-weight: bolder;\r\n");
      out.write("    font-size: 40px;line-height: 60px;margin: 0px\">\r\n");
      out.write("      <p1>更多源码：<a href=\"http://www.mycodes.net/\" target=\"_blank\" style=\"display: none\">源码之家</a></p1>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div align=\"left\" style=\"height:100%;width: 100%;left:200px;top: 60px;position: absolute;\">\r\n");
      out.write("     <iframe name=\"contentiframe\" name=\"content\" style=\"background-color: ghostwhite;height:100%;width: 100%;text-align: center\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
